---
driver_plugin: vagrant

provisioner:
  name: chef_zero

transport:
  name: winrm

platforms:
- name: windows-2012R2
  driver_config:
    box: win2012r2-datacenter-chef11.16.2
    vm_hostname: fourthcoffee

suites:
- name: default
  run_list:
    - 'recipe[fourthcoffee]'
  attributes:
