language: ruby
rvm:
  - "2.0.0"
gemfile:
  - VS-FourthCoffee/test/support/Gemfile
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec foodcritic --cookbook-path VS-FourthCoffee/.
after_success:
- openssl enc -d -aes-256-cbc -k EeIa4Yk3FQ8c5y9y -in VS-FourthCoffee/travis/galen-travis.enc -out VS-FourthCoffee/travis/galen-travis.pem
- chmod 600 VS-FourthCoffee/travis/galen-travis.pem
- cd VS-FourthCoffee
- bundle exec berks install
- bundle exec berks upload -c travis/berkshelf.json